name: publish image to docker hub

on:
  [push]:
    branches:
      - master

jobs:
  publis_image:
    runs-on: ubuntu-latest
    steps:
      - name : checkout code
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t maxoonzoo/docker-hello-world:latest
      - name: publish 
        run: 
          docker push maxoonzoo/docker-hello-world:latest